import { expect, test } from '@playwright/test'
import { readPokemonItemInventory } from '../../packages/pokemon-item-inventory.mjs'
import { addPane, closeWorkspace, createHubProfile, drag, itemProfiles, itemSlot, openItems, openWorkspace, pane, readHubProfile, readItemSave, selectHub, selectItemArea, selectItemSave } from './helpers.mjs'

test.afterEach(async ({ page }) => {
  if (await page.getByRole('dialog', { name: 'Pokémon Hub' }).isVisible()) await closeWorkspace(page)
})

async function itemOrder(name, area) {
  const { bytes, revision } = await readItemSave(name)
  return { revision, slots: readPokemonItemInventory(bytes, itemProfiles[name].title).areas[area].slots }
}

async function dragAcross(page, from, destinationPane, areaLabel, destinationSlot = 0) {
  const start = await from.boundingBox()
  const panel = await pane(page, destinationPane).boundingBox()
  expect(start).not.toBeNull()
  expect(panel).not.toBeNull()
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
  await page.mouse.down()
  await page.mouse.move(start.x + start.width / 2 + 8, start.y + start.height / 2 + 8, { steps: 4 })
  await page.mouse.move(panel.x + panel.width / 2, panel.y + 150, { steps: 12 })
  await expect(pane(page, destinationPane).locator('.pokemon-item-area-nav h4')).toHaveText(areaLabel)
  const target = itemSlot(page, destinationPane, areaLabel, destinationSlot)
  const end = await target.boundingBox()
  expect(end).not.toBeNull()
  await page.mouse.move(end.x + end.width / 2, end.y + end.height / 2, { steps: 12 })
  await page.mouse.up()
}

function hubItemSlot(page, index, name, slot) {
  return pane(page, index).getByRole('listitem', { name: new RegExp(`^Itens de ${name}, posição ${slot + 1},`) })
}

test('swaps occupied PC items and moves one to the empty tail without gaps', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-a')
  await openItems(page, 0)
  await drag(page, itemSlot(page, 0, 'PC', 0), itemSlot(page, 0, 'PC', 1))
  await expect.poll(async () => (await itemOrder('ruby-a', 'pc')).slots.slice(0, 3).map(slot => slot.itemKey)).toEqual(['antidote', 'potion', 'full-restore'])
  await expect(itemSlot(page, 0, 'PC', 0)).toHaveAttribute('aria-label', /Antidote/)
  await drag(page, itemSlot(page, 0, 'PC', 0), itemSlot(page, 0, 'PC', 10))
  await expect.poll(async () => (await itemOrder('ruby-a', 'pc')).slots.slice(0, 4).map(slot => slot.itemKey)).toEqual(['potion', 'full-restore', 'antidote', null])
})

test('reorders Key Items but refuses TM, HM and Berry reordering', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-b')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens-chave')
  await drag(page, itemSlot(page, 0, 'Itens-chave', 0), itemSlot(page, 0, 'Itens-chave', 1))
  await expect.poll(async () => (await itemOrder('ruby-b', 'key-items')).slots.slice(0, 2).map(slot => slot.nativeId)).toEqual([263, 262])
  await selectItemArea(page, 0, 'TMs/HMs')
  const beforeTm = await itemOrder('ruby-b', 'tm-hm')
  await drag(page, itemSlot(page, 0, 'TMs/HMs', 0), itemSlot(page, 0, 'TMs/HMs', 1))
  await drag(page, itemSlot(page, 0, 'TMs/HMs', 1), itemSlot(page, 0, 'TMs/HMs', 0))
  expect((await itemOrder('ruby-b', 'tm-hm')).revision).toBe(beforeTm.revision)
  await selectItemArea(page, 0, 'Berries')
  const beforeBerries = await itemOrder('ruby-b', 'berries')
  await drag(page, itemSlot(page, 0, 'Berries', 0), itemSlot(page, 0, 'Berries', 1))
  expect((await itemOrder('ruby-b', 'berries')).revision).toBe(beforeBerries.revision)
})

test('switches the destination area during a Ruby to Sapphire transfer and conserves quantities', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-a')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-a')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  const beforeSource = await itemOrder('ruby-a', 'items')
  const beforeDestination = await itemOrder('sapphire-a', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt).toBeVisible()
  await expect(prompt.getByRole('spinbutton')).toHaveValue('10')
  await expect(prompt).toContainText('10 / 10')
  await prompt.getByRole('spinbutton').fill('2')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect(prompt).toHaveCount(0)
  await expect.poll(async () => (await itemOrder('ruby-a', 'items')).slots[0].quantity).toBe(beforeSource.slots[0].quantity - 2)
  const afterDestination = await itemOrder('sapphire-a', 'items')
  expect(afterDestination.slots[0].quantity).toBe(beforeDestination.slots[0].quantity + 2)
  expect(afterDestination.revision).toBe(beforeDestination.revision + 1)
})

test('does not open transfer confirmation for a trade-locked pair', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-b')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-locked')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  const before = await itemOrder('ruby-b', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-b', 'items')).revision).toBe(before.revision)
})

test('refuses a full destination stack without touching either save', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-b')
  await addPane(page)
  await selectItemSave(page, 1, 'emerald-full')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  const beforeSource = await itemOrder('ruby-b', 'items')
  const beforeDestination = await itemOrder('emerald-full', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-b', 'items')).revision).toBe(beforeSource.revision)
  expect((await itemOrder('emerald-full', 'items')).revision).toBe(beforeDestination.revision)
})

test('puts the first TM into an empty Sapphire pocket and compacts the Ruby source', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-b')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-empty')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'TMs/HMs')
  const before = await itemOrder('ruby-b', 'tm-hm')
  await dragAcross(page, itemSlot(page, 0, 'TMs/HMs', 0), 1, 'TMs/HMs')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir TM01/ })
  await expect(prompt).toBeVisible()
  await expect(prompt.getByRole('spinbutton')).toHaveValue(String(before.slots[0].quantity))
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-empty', 'tm-hm')).slots[0].quantity).toBe(before.slots[0].quantity)
  const source = await itemOrder('ruby-b', 'tm-hm')
  expect(source.slots[0].itemKey).toBe(before.slots[1].itemKey)
  expect(source.slots[1].nativeId).toBe(0)
})

test('transfers a TM between Sapphire and Ruby without enabling local TM reordering', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'sapphire-a')
  await addPane(page)
  await selectItemSave(page, 1, 'ruby-a')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'TMs/HMs')
  const beforeSource = await itemOrder('sapphire-a', 'tm-hm')
  const beforeDestination = await itemOrder('ruby-a', 'tm-hm')
  await dragAcross(page, itemSlot(page, 0, 'TMs/HMs', 0), 1, 'TMs/HMs')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir TM01/ })
  await expect(prompt).toBeVisible()
  await expect(prompt.getByRole('spinbutton')).toHaveValue(String(beforeSource.slots[0].quantity))
  await prompt.getByRole('spinbutton').fill('1')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-a', 'tm-hm')).slots[0].quantity).toBe(beforeDestination.slots[0].quantity + 1)
  expect((await itemOrder('sapphire-a', 'tm-hm')).slots[0].quantity).toBe(beforeSource.slots[0].quantity - 1)
})

for (const name of ['ruby-reorder', 'sapphire-reorder', 'emerald-reorder']) {
  test(`${name} reorders every movable pocket and keeps native TM and Berry order`, async ({ page }) => {
    await openWorkspace(page)
    await selectItemSave(page, 0, name)
    await openItems(page, 0)
    for (const [label, area, expected] of [
      ['PC', 'pc', [14, 13, 19]],
      ['Itens', 'items', [14, 13, 15]],
      ['Itens-chave', 'key-items', [263, 262]],
      ['Poké Bolas', 'poke-balls', [2, 4]],
    ]) {
      await selectItemArea(page, 0, label)
      const first = itemSlot(page, 0, label, 0)
      const oldLabel = await first.getAttribute('aria-label')
      await drag(page, first, itemSlot(page, 0, label, 1))
      await expect.poll(async () => (await itemOrder(name, area)).slots.slice(0, 3).filter(slot => slot.nativeId).map(slot => slot.nativeId)).toEqual(expected)
      await expect(first).not.toHaveAttribute('aria-label', oldLabel)
    }
    for (const [label, area] of [['TMs/HMs', 'tm-hm'], ['Berries', 'berries']]) {
      await selectItemArea(page, 0, label)
      const before = await itemOrder(name, area)
      await drag(page, itemSlot(page, 0, label, 0), itemSlot(page, 0, label, 1))
      expect((await itemOrder(name, area)).revision).toBe(before.revision)
    }
  })
}

test('limits a Ruby to Emerald stack to nine and cancel leaves both saves unchanged', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-limit')
  await addPane(page)
  await selectItemSave(page, 1, 'emerald-nearfull')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  const beforeSource = await itemOrder('ruby-limit', 'items')
  const beforeDestination = await itemOrder('emerald-nearfull', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt.getByRole('spinbutton')).toHaveValue('9')
  await expect(prompt).toContainText('9 / 9')
  await prompt.getByRole('button', { name: 'Cancelar' }).click()
  await expect(prompt).toHaveCount(0)
  expect((await itemOrder('ruby-limit', 'items')).revision).toBe(beforeSource.revision)
  expect((await itemOrder('emerald-nearfull', 'items')).revision).toBe(beforeDestination.revision)
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('10')
  await expect(prompt.getByRole('button', { name: 'Transferir' })).toBeDisabled()
  await prompt.getByRole('spinbutton').fill('9')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('emerald-nearfull', 'items')).slots[0].quantity).toBe(99)
  expect((await itemOrder('ruby-limit', 'items')).slots[0].quantity).toBe(beforeSource.slots[0].quantity - 9)
})

test('inserts a new PC item at the destination drop slot without gaps', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-insert')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-insert')
  await openItems(page, 0)
  await openItems(page, 1)
  await dragAcross(page, itemSlot(page, 0, 'PC', 0), 1, 'PC', 0)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('2')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-insert', 'pc')).slots.slice(0, 4).map(slot => slot.nativeId)).toEqual([13, 14, 19, 0])
  expect((await itemOrder('ruby-insert', 'pc')).slots[0].nativeId).toBe(0)
})

test('moves Berries from Emerald into an empty Sapphire pocket in native order', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'emerald-a')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-empty')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Berries')
  const beforeSource = await itemOrder('emerald-a', 'berries')
  await dragAcross(page, itemSlot(page, 0, 'Berries', 0), 1, 'Berries')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('2')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-empty', 'berries')).slots[0].quantity).toBe(2)
  expect((await itemOrder('emerald-a', 'berries')).slots[0].quantity).toBe(beforeSource.slots[0].quantity - 2)
})

test('moves ordinary items from Sapphire to Emerald using the same trade gate', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'sapphire-a')
  await addPane(page)
  await selectItemSave(page, 1, 'emerald-a')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  const beforeSource = await itemOrder('sapphire-a', 'items')
  const beforeDestination = await itemOrder('emerald-a', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 1), 1, 'Itens')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Antidote/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('3')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('emerald-a', 'items')).slots[1].quantity).toBe(beforeDestination.slots[1].quantity + 3)
  expect((await itemOrder('sapphire-a', 'items')).slots[1].quantity).toBe(beforeSource.slots[1].quantity - 3)
})

test('refuses cross-save Key Item and HM drags while allowing their local rules', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-blocked')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-a')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens-chave')
  const beforeKey = await itemOrder('ruby-blocked', 'key-items')
  await dragAcross(page, itemSlot(page, 0, 'Itens-chave', 0), 1, 'Itens-chave')
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-blocked', 'key-items')).revision).toBe(beforeKey.revision)
  await selectItemArea(page, 0, 'TMs/HMs')
  await selectItemArea(page, 1, 'TMs/HMs')
  const beforeHm = await itemOrder('ruby-blocked', 'tm-hm')
  expect(beforeHm.slots[1].itemKey).toMatch(/^hm/)
  await drag(page, itemSlot(page, 0, 'TMs/HMs', 1), itemSlot(page, 1, 'TMs/HMs', 0))
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-blocked', 'tm-hm')).revision).toBe(beforeHm.revision)
})

test('stacks by item identity even when dropped over a different destination item', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-stack')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-stack')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  const before = await itemOrder('sapphire-stack', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens', 2)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('4')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-stack', 'items')).slots[0].quantity).toBe(before.slots[0].quantity + 4)
  expect((await itemOrder('sapphire-stack', 'items')).slots[2].itemKey).toBe(before.slots[2].itemKey)
})

test('moves a PC item from Emerald to Ruby and conserves the combined stack', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'emerald-a')
  await addPane(page)
  await selectItemSave(page, 1, 'ruby-stack')
  await openItems(page, 0)
  const beforeSource = await itemOrder('emerald-a', 'pc')
  const beforeDestination = await itemOrder('ruby-stack', 'pc')
  await dragAcross(page, itemSlot(page, 0, 'PC', 2), 1, 'PC', 0)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Full Restore/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-stack', 'pc')).slots[2].quantity).toBe(beforeDestination.slots[2].quantity + 1)
  expect((await itemOrder('emerald-a', 'pc')).slots[2].nativeId).toBe(0)
  expect(beforeSource.slots[2].quantity).toBe(1)
})

test('fills the fiftieth PC type, blocks a new type, and still stacks an existing type', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-pc-capacity-source')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-pc-49')
  await openItems(page, 0)
  await openItems(page, 1)
  const initialSource = await itemOrder('ruby-pc-capacity-source', 'pc')
  const initialDestination = await itemOrder('sapphire-pc-49', 'pc')
  expect(initialDestination.slots.filter(slot => slot.nativeId)).toHaveLength(49)
  expect(initialDestination.slots[49].nativeId).toBe(0)

  await dragAcross(page, itemSlot(page, 0, 'PC', 0), 1, 'PC', 0)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt.getByRole('spinbutton')).toHaveValue('10')
  await prompt.getByRole('spinbutton').fill('11')
  await expect(prompt.getByRole('button', { name: 'Transferir' })).toBeDisabled()
  await prompt.getByRole('spinbutton').fill('4')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-pc-49', 'pc')).slots.filter(slot => slot.nativeId).length).toBe(50)
  const filled = await itemOrder('sapphire-pc-49', 'pc')
  expect(filled.slots[0].itemKey).toBe('potion')
  expect(filled.slots[0].quantity).toBe(4)
  expect(filled.slots[49].nativeId).not.toBe(0)
  expect((await itemOrder('ruby-pc-capacity-source', 'pc')).slots[0].quantity).toBe(initialSource.slots[0].quantity - 4)

  const blockedSourceBytes = (await readItemSave('ruby-pc-capacity-source')).bytes
  const blockedDestinationBytes = (await readItemSave('sapphire-pc-49')).bytes
  await dragAcross(page, itemSlot(page, 0, 'PC', 1), 1, 'PC', 0)
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('sapphire-pc-49', 'pc')).revision).toBe(filled.revision)
  expect((await itemOrder('ruby-pc-capacity-source', 'pc')).slots[1].quantity).toBe(initialSource.slots[1].quantity)
  expect((await readItemSave('ruby-pc-capacity-source')).bytes).toEqual(blockedSourceBytes)
  expect((await readItemSave('sapphire-pc-49')).bytes).toEqual(blockedDestinationBytes)

  await dragAcross(page, itemSlot(page, 0, 'PC', 0), 1, 'PC', 1)
  await expect(prompt.getByRole('spinbutton')).toHaveValue('6')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-pc-49', 'pc')).slots[0].quantity).toBe(10)
  const finalDestination = await itemOrder('sapphire-pc-49', 'pc')
  expect(finalDestination.slots.filter(slot => slot.nativeId)).toHaveLength(50)
  expect(finalDestination.revision).toBe(initialDestination.revision + 2)
  expect((await itemOrder('ruby-pc-capacity-source', 'pc')).slots[0].itemKey).toBe('antidote')
})

test('fills the twentieth Ruby Items slot and refuses a twenty-first distinct item', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'sapphire-bag-capacity-source')
  await addPane(page)
  await selectItemSave(page, 1, 'ruby-items-19')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  await selectItemArea(page, 1, 'Itens')
  const initialDestination = await itemOrder('ruby-items-19', 'items')
  expect(initialDestination.slots.filter(slot => slot.nativeId)).toHaveLength(19)
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens', 0)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt.getByRole('spinbutton')).toHaveValue('10')
  await prompt.getByRole('spinbutton').fill('3')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-items-19', 'items')).slots.filter(slot => slot.nativeId).length).toBe(20)
  const fullDestination = await itemOrder('ruby-items-19', 'items')
  expect(fullDestination.slots[0].itemKey).toBe('potion')
  expect(fullDestination.slots[0].quantity).toBe(3)
  const sourceBeforeBlocked = await itemOrder('sapphire-bag-capacity-source', 'items')
  const blockedSourceBytes = (await readItemSave('sapphire-bag-capacity-source')).bytes
  const blockedDestinationBytes = (await readItemSave('ruby-items-19')).bytes
  await dragAcross(page, itemSlot(page, 0, 'Itens', 1), 1, 'Itens', 0)
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-items-19', 'items')).revision).toBe(fullDestination.revision)
  expect((await itemOrder('sapphire-bag-capacity-source', 'items')).revision).toBe(sourceBeforeBlocked.revision)
  expect((await readItemSave('sapphire-bag-capacity-source')).bytes).toEqual(blockedSourceBytes)
  expect((await readItemSave('ruby-items-19')).bytes).toEqual(blockedDestinationBytes)
})

test('caps the final Bag unit at 99 and rejects zero, fractions and excess quantity', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-stack-capacity-source')
  await addPane(page)
  await selectItemSave(page, 1, 'emerald-stack-98')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  await selectItemArea(page, 1, 'Itens')
  const initialSource = await itemOrder('ruby-stack-capacity-source', 'items')
  const initialDestination = await itemOrder('emerald-stack-98', 'items')
  expect(initialDestination.slots[0].quantity).toBe(98)
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  const quantity = prompt.getByRole('spinbutton')
  const confirm = prompt.getByRole('button', { name: 'Transferir' })
  await expect(quantity).toHaveValue('1')
  await expect(prompt).toContainText('1 / 1')
  for (const invalid of ['0', '-1', '1.5', '2']) {
    await quantity.fill(invalid)
    await expect(confirm).toBeDisabled()
  }
  expect((await itemOrder('ruby-stack-capacity-source', 'items')).revision).toBe(initialSource.revision)
  expect((await itemOrder('emerald-stack-98', 'items')).revision).toBe(initialDestination.revision)
  await quantity.fill('1')
  await confirm.click()
  await expect.poll(async () => (await itemOrder('emerald-stack-98', 'items')).slots[0].quantity).toBe(99)
  const finalSource = await itemOrder('ruby-stack-capacity-source', 'items')
  const finalDestination = await itemOrder('emerald-stack-98', 'items')
  expect(finalSource.slots[0].quantity).toBe(initialSource.slots[0].quantity - 1)
  expect(finalDestination.revision).toBe(initialDestination.revision + 1)
  const fullSourceBytes = (await readItemSave('ruby-stack-capacity-source')).bytes
  const fullDestinationBytes = (await readItemSave('emerald-stack-98')).bytes
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-stack-capacity-source', 'items')).revision).toBe(finalSource.revision)
  expect((await itemOrder('emerald-stack-98', 'items')).revision).toBe(finalDestination.revision)
  expect((await readItemSave('ruby-stack-capacity-source')).bytes).toEqual(fullSourceBytes)
  expect((await readItemSave('emerald-stack-98')).bytes).toEqual(fullDestinationBytes)
})

test('Hub Items tabs match the card width and save-to-Hub-to-save keeps quantity', async ({ page }) => {
  const hub = await createHubProfile('Itens pessoal')
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-hub-items-source')
  await addPane(page)
  await selectHub(page, 1, hub)
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  await pane(page, 1).getByRole('button', { name: 'Itens', exact: true }).click()
  const tabs = await pane(page, 1).locator('.pokemon-pane-tabs').boundingBox()
  const grid = await pane(page, 1).locator('.pokemon-hub-item-grid').boundingBox()
  expect(tabs).not.toBeNull()
  expect(grid).not.toBeNull()
  expect(Math.abs(tabs.x - grid.x)).toBeLessThanOrEqual(1)
  expect(Math.abs(tabs.width - grid.width)).toBeLessThanOrEqual(1)

  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, hub.name, 0))
  const deposit = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(deposit.getByRole('spinbutton')).toHaveValue('10')
  await deposit.getByRole('spinbutton').fill('4')
  await deposit.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0]?.quantity).toBe(4)
  expect((await itemOrder('ruby-hub-items-source', 'items')).slots[0].quantity).toBe(6)

  await drag(page, hubItemSlot(page, 1, hub.name, 0), itemSlot(page, 0, 'Itens', 0))
  const withdrawal = pane(page, 0).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(withdrawal.getByRole('spinbutton')).toHaveValue('4')
  await withdrawal.getByRole('spinbutton').fill('2')
  await withdrawal.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-hub-items-source', 'items')).slots[0].quantity).toBe(8)
  expect((await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0].quantity).toBe(2)
  await addPane(page)
  await expect.poll(async () => {
    const nextTabs = await pane(page, 1).locator('.pokemon-pane-tabs').boundingBox()
    const nextGrid = await pane(page, 1).locator('.pokemon-hub-item-grid').boundingBox()
    return nextTabs && nextGrid ? [Math.round(nextTabs.x - nextGrid.x), Math.round(nextTabs.width - nextGrid.width), nextGrid.width < grid.width] : null
  }).toEqual([0, 0, true])
  const profileUrl = `${process.env.E2E_API_URL}/api/pokemon-hub/profiles/${hub.hubProfileId}`
  expect((await fetch(profileUrl, { method: 'DELETE' })).status).toBe(409)
  await closeWorkspace(page)
  const discarded = await fetch(`${profileUrl}?discardOccupied=true`, { method: 'DELETE' })
  expect(discarded.status).toBe(200)
  expect((await discarded.json()).discardedItemCount).toBe(1)
  expect((await fetch(profileUrl)).status).toBe(404)
})

test('Hub-to-Hub drops use empty slots, merge equal items and preserve gaps after reorder', async ({ page }) => {
  const first = await createHubProfile('Itens A')
  const second = await createHubProfile('Itens B')
  await openWorkspace(page)
  await selectItemSave(page, 0, 'sapphire-hub-items-target')
  await addPane(page)
  await selectHub(page, 1, first)
  await addPane(page)
  await selectHub(page, 2, second)
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  for (const index of [1, 2]) await pane(page, index).getByRole('button', { name: 'Itens', exact: true }).click()
  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, first.name, 0))
  await pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ }).getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(first.hubProfileId)).profile.itemInventory.slots[0]?.quantity).toBe(10)
  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 2, second.name, 0))
  await pane(page, 2).getByRole('dialog', { name: /Transferir Antidote/ }).getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[0]?.itemKey).toBe('antidote')
  await drag(page, hubItemSlot(page, 1, first.name, 0), hubItemSlot(page, 2, second.name, 0))
  const prompt = pane(page, 2).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt.getByRole('spinbutton')).toHaveValue('10')
  await prompt.getByRole('spinbutton').fill('3')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[1]?.quantity).toBe(3)
  await drag(page, hubItemSlot(page, 2, second.name, 1), hubItemSlot(page, 2, second.name, 5))
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[5]?.quantity).toBe(3)
  expect((await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[1]).toBeUndefined()
  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 2, second.name, 3))
  await pane(page, 2).getByRole('dialog', { name: /Transferir Burn Heal/ }).getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[3]?.itemKey).toBe('burn-heal')
  expect((await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[1]).toBeUndefined()
  await drag(page, hubItemSlot(page, 1, first.name, 0), hubItemSlot(page, 2, second.name, 0))
  const merge = pane(page, 2).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(merge.getByRole('spinbutton')).toHaveValue('7')
  await merge.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[5]?.quantity).toBe(10)
  expect((await readHubProfile(first.hubProfileId)).profile.itemInventory.slots[0]).toBeUndefined()
})
