import { expect, test } from '@playwright/test'
import { readPokemonItemInventory } from '../../packages/pokemon-item-inventory.mjs'
import { addPane, closeWorkspace, createHubProfile, drag, forgetSelectedSaves, itemProfiles, itemSlot, openItems, openWorkspace, pane, readHubProfile, readItemSave, selectHub, selectItemArea, selectItemSave } from './helpers.mjs'
import { watchSnapshots } from './snapshot-audit.mjs'

const audits = new WeakMap()
test.beforeEach(async ({ page }) => { audits.set(page, await watchSnapshots(page)) })
test.afterEach(async ({ page }, testInfo) => {
  try {
    if (await page.getByRole('dialog', { name: 'Pokémon Hub' }).isVisible()) await closeWorkspace(page)
  } finally { await audits.get(page)(testInfo) }
})

async function itemOrder(name, area) {
  const { bytes, revision } = await readItemSave(name)
  return { revision, slots: readPokemonItemInventory(bytes, itemProfiles[name].title).areas[area].slots }
}

async function dragAcross(page, from, destinationPane, areaLabel, destinationSlot = 0) {
  const start = await from.boundingBox()
  const panel = await pane(page, destinationPane).boundingBox()
  expect(start).not.toBeNull()
  expect(panel).not.toBeNull()
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
  await page.mouse.down()
  await page.mouse.move(start.x + start.width / 2 + 8, start.y + start.height / 2 + 8, { steps: 4 })
  await page.mouse.move(panel.x + panel.width / 2, panel.y + 150, { steps: 12 })
  await expect(pane(page, destinationPane).locator('.pokemon-item-area-nav h4')).toHaveText(areaLabel)
  const target = itemSlot(page, destinationPane, areaLabel, destinationSlot)
  const end = await target.boundingBox()
  expect(end).not.toBeNull()
  await page.mouse.move(end.x + end.width / 2, end.y + end.height / 2, { steps: 12 })
  await page.mouse.up()
}

function hubItemSlot(page, index, name, slot) {
  return pane(page, index).getByRole('listitem', { name: new RegExp(`^Itens de ${name}, posição ${slot + 1},`) })
}

test('swaps occupied PC items and moves one to the empty tail without gaps', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-a')
  await openItems(page, 0)
  await drag(page, itemSlot(page, 0, 'PC', 0), itemSlot(page, 0, 'PC', 1))
  await expect.poll(async () => (await itemOrder('ruby-a', 'pc')).slots.slice(0, 3).map(slot => slot.itemKey)).toEqual(['antidote', 'potion', 'full-restore'])
  await expect(itemSlot(page, 0, 'PC', 0)).toHaveAttribute('aria-label', /Antidote/)
  await drag(page, itemSlot(page, 0, 'PC', 0), itemSlot(page, 0, 'PC', 10))
  await expect.poll(async () => (await itemOrder('ruby-a', 'pc')).slots.slice(0, 4).map(slot => slot.itemKey)).toEqual(['potion', 'full-restore', 'antidote', null])
})

test('reorders Key Items but refuses TM, HM and Berry reordering', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-b')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens-chave')
  await drag(page, itemSlot(page, 0, 'Itens-chave', 0), itemSlot(page, 0, 'Itens-chave', 1))
  await expect.poll(async () => (await itemOrder('ruby-b', 'key-items')).slots.slice(0, 2).map(slot => slot.nativeId)).toEqual([263, 262])
  await selectItemArea(page, 0, 'TMs/HMs')
  const beforeTm = await itemOrder('ruby-b', 'tm-hm')
  await drag(page, itemSlot(page, 0, 'TMs/HMs', 0), itemSlot(page, 0, 'TMs/HMs', 1))
  await drag(page, itemSlot(page, 0, 'TMs/HMs', 1), itemSlot(page, 0, 'TMs/HMs', 0))
  expect((await itemOrder('ruby-b', 'tm-hm')).revision).toBe(beforeTm.revision)
  await selectItemArea(page, 0, 'Berries')
  const beforeBerries = await itemOrder('ruby-b', 'berries')
  await drag(page, itemSlot(page, 0, 'Berries', 0), itemSlot(page, 0, 'Berries', 1))
  expect((await itemOrder('ruby-b', 'berries')).revision).toBe(beforeBerries.revision)
})

test('switches the destination area during a Ruby to Sapphire transfer and conserves quantities', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-a')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-a')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  const beforeSource = await itemOrder('ruby-a', 'items')
  const beforeDestination = await itemOrder('sapphire-a', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt).toBeVisible()
  await expect(prompt.getByRole('spinbutton')).toHaveValue('10')
  await expect(prompt.locator('.pokemon-item-transfer-identity img.pokemon-item-sprite')).toHaveAttribute('src', /potion/)
  await expect(prompt.getByText('Quantidade a transferir')).toBeVisible()
  await expect(prompt.locator('.pokemon-item-transfer-limit')).toHaveText('/ 10')
  await expect(prompt).not.toContainText('Máximo transferível')
  await expect(prompt).not.toContainText('No destino')
  await prompt.getByRole('spinbutton').fill('2')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect(prompt).toHaveCount(0)
  await expect.poll(async () => (await itemOrder('ruby-a', 'items')).slots[0].quantity).toBe(beforeSource.slots[0].quantity - 2)
  const afterDestination = await itemOrder('sapphire-a', 'items')
  expect(afterDestination.slots[0].quantity).toBe(beforeDestination.slots[0].quantity + 2)
  expect(afterDestination.revision).toBe(beforeDestination.revision + 1)
})

test('does not open transfer confirmation for a trade-locked pair', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-b')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-locked')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  const before = await itemOrder('ruby-b', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-b', 'items')).revision).toBe(before.revision)
})

test('refuses a full destination stack without touching either save', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-b')
  await addPane(page)
  await selectItemSave(page, 1, 'emerald-full')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  const beforeSource = await itemOrder('ruby-b', 'items')
  const beforeDestination = await itemOrder('emerald-full', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-b', 'items')).revision).toBe(beforeSource.revision)
  expect((await itemOrder('emerald-full', 'items')).revision).toBe(beforeDestination.revision)
})

test('puts the first TM into an empty Sapphire pocket and compacts the Ruby source', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-b')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-empty')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'TMs/HMs')
  const before = await itemOrder('ruby-b', 'tm-hm')
  await dragAcross(page, itemSlot(page, 0, 'TMs/HMs', 0), 1, 'TMs/HMs')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir TM01/ })
  await expect(prompt).toBeVisible()
  await expect(prompt.getByRole('spinbutton')).toHaveValue(String(before.slots[0].quantity))
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-empty', 'tm-hm')).slots[0].quantity).toBe(before.slots[0].quantity)
  const source = await itemOrder('ruby-b', 'tm-hm')
  expect(source.slots[0].itemKey).toBe(before.slots[1].itemKey)
  expect(source.slots[1].nativeId).toBe(0)
})

test('transfers a TM between Sapphire and Ruby without enabling local TM reordering', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'sapphire-a')
  await addPane(page)
  await selectItemSave(page, 1, 'ruby-a')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'TMs/HMs')
  const beforeSource = await itemOrder('sapphire-a', 'tm-hm')
  const beforeDestination = await itemOrder('ruby-a', 'tm-hm')
  await dragAcross(page, itemSlot(page, 0, 'TMs/HMs', 0), 1, 'TMs/HMs')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir TM01/ })
  await expect(prompt).toBeVisible()
  await expect(prompt.getByRole('spinbutton')).toHaveValue(String(beforeSource.slots[0].quantity))
  await prompt.getByRole('spinbutton').fill('1')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-a', 'tm-hm')).slots[0].quantity).toBe(beforeDestination.slots[0].quantity + 1)
  expect((await itemOrder('sapphire-a', 'tm-hm')).slots[0].quantity).toBe(beforeSource.slots[0].quantity - 1)
})

for (const name of ['ruby-reorder', 'sapphire-reorder', 'emerald-reorder']) {
  test(`${name} reorders every movable pocket and keeps native TM and Berry order`, async ({ page }) => {
    await openWorkspace(page)
    await selectItemSave(page, 0, name)
    await openItems(page, 0)
    for (const [label, area, expected] of [
      ['PC', 'pc', [14, 13, 19]],
      ['Itens', 'items', [14, 13, 15]],
      ['Itens-chave', 'key-items', [263, 262]],
      ['Poké Bolas', 'poke-balls', [2, 4]],
    ]) {
      await selectItemArea(page, 0, label)
      const first = itemSlot(page, 0, label, 0)
      const oldLabel = await first.getAttribute('aria-label')
      await drag(page, first, itemSlot(page, 0, label, 1))
      await expect.poll(async () => (await itemOrder(name, area)).slots.slice(0, 3).filter(slot => slot.nativeId).map(slot => slot.nativeId)).toEqual(expected)
      await expect(first).not.toHaveAttribute('aria-label', oldLabel)
    }
    for (const [label, area] of [['TMs/HMs', 'tm-hm'], ['Berries', 'berries']]) {
      await selectItemArea(page, 0, label)
      const before = await itemOrder(name, area)
      await drag(page, itemSlot(page, 0, label, 0), itemSlot(page, 0, label, 1))
      expect((await itemOrder(name, area)).revision).toBe(before.revision)
    }
  })
}

test('limits a Ruby to Emerald stack to nine and cancel leaves both saves unchanged', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-limit')
  await addPane(page)
  await selectItemSave(page, 1, 'emerald-nearfull')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  const beforeSource = await itemOrder('ruby-limit', 'items')
  const beforeDestination = await itemOrder('emerald-nearfull', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt.getByRole('spinbutton')).toHaveValue('9')
  await expect(prompt.locator('.pokemon-item-transfer-limit')).toHaveText('/ 9')
  await prompt.getByRole('button', { name: 'Cancelar' }).click()
  await expect(prompt).toHaveCount(0)
  expect((await itemOrder('ruby-limit', 'items')).revision).toBe(beforeSource.revision)
  expect((await itemOrder('emerald-nearfull', 'items')).revision).toBe(beforeDestination.revision)
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('10')
  await expect(prompt.getByRole('button', { name: 'Transferir' })).toBeDisabled()
  await prompt.getByRole('spinbutton').fill('9')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('emerald-nearfull', 'items')).slots[0].quantity).toBe(99)
  expect((await itemOrder('ruby-limit', 'items')).slots[0].quantity).toBe(beforeSource.slots[0].quantity - 9)
})

test('inserts a new PC item at the destination drop slot without gaps', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-insert')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-insert')
  await openItems(page, 0)
  await openItems(page, 1)
  await dragAcross(page, itemSlot(page, 0, 'PC', 0), 1, 'PC', 0)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('2')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-insert', 'pc')).slots.slice(0, 4).map(slot => slot.nativeId)).toEqual([13, 14, 19, 0])
  expect((await itemOrder('ruby-insert', 'pc')).slots[0].nativeId).toBe(0)
})

test('moves Berries from Emerald into an empty Sapphire pocket in native order', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'emerald-a')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-empty')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Berries')
  const beforeSource = await itemOrder('emerald-a', 'berries')
  await dragAcross(page, itemSlot(page, 0, 'Berries', 0), 1, 'Berries')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('2')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-empty', 'berries')).slots[0].quantity).toBe(2)
  expect((await itemOrder('emerald-a', 'berries')).slots[0].quantity).toBe(beforeSource.slots[0].quantity - 2)
})

test('moves ordinary items from Sapphire to Emerald using the same trade gate', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'sapphire-a')
  await addPane(page)
  await selectItemSave(page, 1, 'emerald-a')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  const beforeSource = await itemOrder('sapphire-a', 'items')
  const beforeDestination = await itemOrder('emerald-a', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 1), 1, 'Itens')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Antidote/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('3')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('emerald-a', 'items')).slots[1].quantity).toBe(beforeDestination.slots[1].quantity + 3)
  expect((await itemOrder('sapphire-a', 'items')).slots[1].quantity).toBe(beforeSource.slots[1].quantity - 3)
})

test('refuses cross-save Key Item and HM drags while allowing their local rules', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-blocked')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-a')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens-chave')
  const beforeKey = await itemOrder('ruby-blocked', 'key-items')
  await dragAcross(page, itemSlot(page, 0, 'Itens-chave', 0), 1, 'Itens-chave')
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-blocked', 'key-items')).revision).toBe(beforeKey.revision)
  await selectItemArea(page, 0, 'TMs/HMs')
  await selectItemArea(page, 1, 'TMs/HMs')
  const beforeHm = await itemOrder('ruby-blocked', 'tm-hm')
  expect(beforeHm.slots[1].itemKey).toMatch(/^hm/)
  await drag(page, itemSlot(page, 0, 'TMs/HMs', 1), itemSlot(page, 1, 'TMs/HMs', 0))
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-blocked', 'tm-hm')).revision).toBe(beforeHm.revision)
})

test('shows destination-wide blocked feedback for Key Items and HMs while TMs remain draggable', async ({ page }) => {
  const hub = await createHubProfile('Destino bloqueado')
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-block-feedback')
  await addPane(page)
  await selectHub(page, 1, hub)
  await openItems(page, 0)
  await openItems(page, 1)
  const before = await readItemSave('ruby-block-feedback')
  const blocked = pane(page, 1).getByRole('status', { name: 'Não é possível arrastar esse item.' })
  for (const [area, slot] of [['Itens-chave', 0], ['TMs/HMs', 1]]) {
    await selectItemArea(page, 0, area)
    const origin = itemSlot(page, 0, area, slot)
    await expect(origin).toHaveCSS('cursor', 'grab')
    const from = await origin.boundingBox()
    const target = await hubItemSlot(page, 1, hub.name, 0).boundingBox()
    expect(from).not.toBeNull()
    expect(target).not.toBeNull()
    await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2)
    await page.mouse.down()
    await page.mouse.move(from.x + from.width / 2 + 8, from.y + from.height / 2 + 8, { steps: 4 })
    await page.mouse.move(target.x + target.width / 2, target.y + target.height / 2, { steps: 12 })
    await expect(blocked).toBeVisible()
    const overlayBounds = await blocked.boundingBox()
    const paneBounds = await pane(page, 1).boundingBox()
    expect(Math.abs(overlayBounds.x - paneBounds.x)).toBeLessThanOrEqual(1)
    expect(Math.abs(overlayBounds.y - paneBounds.y)).toBeLessThanOrEqual(1)
    expect(Math.abs(overlayBounds.width - paneBounds.width)).toBeLessThanOrEqual(1)
    expect(Math.abs(overlayBounds.height - paneBounds.height)).toBeLessThanOrEqual(1)
    await expect(pane(page, 0).getByRole('status', { name: 'Não é possível arrastar esse item.' })).toHaveCount(0)
    await expect(blocked.locator('.pokemon-item-block-icon')).toHaveCSS('color', 'rgb(255, 91, 103)')
    await page.mouse.up()
    await expect(blocked).toHaveCount(0)
    await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  }
  expect((await readItemSave('ruby-block-feedback')).revision).toBe(before.revision)
  await expect(itemSlot(page, 0, 'TMs/HMs', 0)).toHaveCSS('cursor', 'grab')
  await drag(page, itemSlot(page, 0, 'TMs/HMs', 0), hubItemSlot(page, 1, hub.name, 0))
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir TM/ })).toBeVisible()
  await pane(page, 1).getByRole('button', { name: 'Cancelar' }).click()
})

test('stacks by item identity even when dropped over a different destination item', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-stack')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-stack')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  const before = await itemOrder('sapphire-stack', 'items')
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens', 2)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('spinbutton').fill('4')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-stack', 'items')).slots[0].quantity).toBe(before.slots[0].quantity + 4)
  expect((await itemOrder('sapphire-stack', 'items')).slots[2].itemKey).toBe(before.slots[2].itemKey)
})

test('moves a PC item from Emerald to Ruby and conserves the combined stack', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'emerald-a')
  await addPane(page)
  await selectItemSave(page, 1, 'ruby-stack')
  await openItems(page, 0)
  const beforeSource = await itemOrder('emerald-a', 'pc')
  const beforeDestination = await itemOrder('ruby-stack', 'pc')
  await dragAcross(page, itemSlot(page, 0, 'PC', 2), 1, 'PC', 0)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Full Restore/ })
  await expect(prompt).toBeVisible()
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-stack', 'pc')).slots[2].quantity).toBe(beforeDestination.slots[2].quantity + 1)
  expect((await itemOrder('emerald-a', 'pc')).slots[2].nativeId).toBe(0)
  expect(beforeSource.slots[2].quantity).toBe(1)
})

test('fills the fiftieth PC type, blocks a new type, and still stacks an existing type', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-pc-capacity-source')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-pc-49')
  await openItems(page, 0)
  await openItems(page, 1)
  const initialSource = await itemOrder('ruby-pc-capacity-source', 'pc')
  const initialDestination = await itemOrder('sapphire-pc-49', 'pc')
  expect(initialDestination.slots.filter(slot => slot.nativeId)).toHaveLength(49)
  expect(initialDestination.slots[49].nativeId).toBe(0)

  await dragAcross(page, itemSlot(page, 0, 'PC', 0), 1, 'PC', 0)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt.getByRole('spinbutton')).toHaveValue('10')
  await prompt.getByRole('spinbutton').fill('11')
  await expect(prompt.getByRole('button', { name: 'Transferir' })).toBeDisabled()
  await prompt.getByRole('spinbutton').fill('4')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-pc-49', 'pc')).slots.filter(slot => slot.nativeId).length).toBe(50)
  const filled = await itemOrder('sapphire-pc-49', 'pc')
  expect(filled.slots[0].itemKey).toBe('potion')
  expect(filled.slots[0].quantity).toBe(4)
  expect(filled.slots[49].nativeId).not.toBe(0)
  expect((await itemOrder('ruby-pc-capacity-source', 'pc')).slots[0].quantity).toBe(initialSource.slots[0].quantity - 4)

  const blockedSourceBytes = (await readItemSave('ruby-pc-capacity-source')).bytes
  const blockedDestinationBytes = (await readItemSave('sapphire-pc-49')).bytes
  await dragAcross(page, itemSlot(page, 0, 'PC', 1), 1, 'PC', 0)
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('sapphire-pc-49', 'pc')).revision).toBe(filled.revision)
  expect((await itemOrder('ruby-pc-capacity-source', 'pc')).slots[1].quantity).toBe(initialSource.slots[1].quantity)
  expect((await readItemSave('ruby-pc-capacity-source')).bytes).toEqual(blockedSourceBytes)
  expect((await readItemSave('sapphire-pc-49')).bytes).toEqual(blockedDestinationBytes)

  await dragAcross(page, itemSlot(page, 0, 'PC', 0), 1, 'PC', 1)
  await expect(prompt.getByRole('spinbutton')).toHaveValue('6')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('sapphire-pc-49', 'pc')).slots[0].quantity).toBe(10)
  const finalDestination = await itemOrder('sapphire-pc-49', 'pc')
  expect(finalDestination.slots.filter(slot => slot.nativeId)).toHaveLength(50)
  expect(finalDestination.revision).toBe(initialDestination.revision + 2)
  expect((await itemOrder('ruby-pc-capacity-source', 'pc')).slots[0].itemKey).toBe('antidote')
})

test('fills the twentieth Ruby Items slot and refuses a twenty-first distinct item', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'sapphire-bag-capacity-source')
  await addPane(page)
  await selectItemSave(page, 1, 'ruby-items-19')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  await selectItemArea(page, 1, 'Itens')
  const initialDestination = await itemOrder('ruby-items-19', 'items')
  expect(initialDestination.slots.filter(slot => slot.nativeId)).toHaveLength(19)
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens', 0)
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt.getByRole('spinbutton')).toHaveValue('10')
  await prompt.getByRole('spinbutton').fill('3')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-items-19', 'items')).slots.filter(slot => slot.nativeId).length).toBe(20)
  const fullDestination = await itemOrder('ruby-items-19', 'items')
  expect(fullDestination.slots[0].itemKey).toBe('potion')
  expect(fullDestination.slots[0].quantity).toBe(3)
  const sourceBeforeBlocked = await itemOrder('sapphire-bag-capacity-source', 'items')
  const blockedSourceBytes = (await readItemSave('sapphire-bag-capacity-source')).bytes
  const blockedDestinationBytes = (await readItemSave('ruby-items-19')).bytes
  await dragAcross(page, itemSlot(page, 0, 'Itens', 1), 1, 'Itens', 0)
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-items-19', 'items')).revision).toBe(fullDestination.revision)
  expect((await itemOrder('sapphire-bag-capacity-source', 'items')).revision).toBe(sourceBeforeBlocked.revision)
  expect((await readItemSave('sapphire-bag-capacity-source')).bytes).toEqual(blockedSourceBytes)
  expect((await readItemSave('ruby-items-19')).bytes).toEqual(blockedDestinationBytes)
})

test('caps the final Bag unit at 99 and rejects zero, fractions and excess quantity', async ({ page }) => {
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-stack-capacity-source')
  await addPane(page)
  await selectItemSave(page, 1, 'emerald-stack-98')
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  await selectItemArea(page, 1, 'Itens')
  const initialSource = await itemOrder('ruby-stack-capacity-source', 'items')
  const initialDestination = await itemOrder('emerald-stack-98', 'items')
  expect(initialDestination.slots[0].quantity).toBe(98)
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  const quantity = prompt.getByRole('spinbutton')
  const confirm = prompt.getByRole('button', { name: 'Transferir' })
  await expect(quantity).toHaveValue('1')
  await expect(prompt.locator('.pokemon-item-transfer-limit')).toHaveText('/ 1')
  for (const invalid of ['0', '-1', '1.5', '2']) {
    await quantity.fill(invalid)
    await expect(confirm).toBeDisabled()
  }
  expect((await itemOrder('ruby-stack-capacity-source', 'items')).revision).toBe(initialSource.revision)
  expect((await itemOrder('emerald-stack-98', 'items')).revision).toBe(initialDestination.revision)
  await quantity.fill('1')
  await confirm.click()
  await expect.poll(async () => (await itemOrder('emerald-stack-98', 'items')).slots[0].quantity).toBe(99)
  const finalSource = await itemOrder('ruby-stack-capacity-source', 'items')
  const finalDestination = await itemOrder('emerald-stack-98', 'items')
  expect(finalSource.slots[0].quantity).toBe(initialSource.slots[0].quantity - 1)
  expect(finalDestination.revision).toBe(initialDestination.revision + 1)
  const fullSourceBytes = (await readItemSave('ruby-stack-capacity-source')).bytes
  const fullDestinationBytes = (await readItemSave('emerald-stack-98')).bytes
  await dragAcross(page, itemSlot(page, 0, 'Itens', 0), 1, 'Itens')
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await itemOrder('ruby-stack-capacity-source', 'items')).revision).toBe(finalSource.revision)
  expect((await itemOrder('emerald-stack-98', 'items')).revision).toBe(finalDestination.revision)
  expect((await readItemSave('ruby-stack-capacity-source')).bytes).toEqual(fullSourceBytes)
  expect((await readItemSave('emerald-stack-98')).bytes).toEqual(fullDestinationBytes)
})

test('Hub Items tabs match the card width and save-to-Hub-to-save keeps quantity', async ({ page }) => {
  const hub = await createHubProfile('Itens pessoal')
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-hub-items-source')
  await addPane(page)
  await selectHub(page, 1, hub)
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  await pane(page, 1).getByRole('button', { name: 'Itens', exact: true }).click()
  const tabs = await pane(page, 1).locator('.pokemon-pane-tabs').boundingBox()
  const grid = await pane(page, 1).locator('.pokemon-hub-item-grid').boundingBox()
  expect(tabs).not.toBeNull()
  expect(grid).not.toBeNull()
  expect(Math.abs(tabs.x - grid.x)).toBeLessThanOrEqual(1)
  expect(Math.abs(tabs.width - grid.width)).toBeLessThanOrEqual(1)
  const hubNav = pane(page, 1).locator('.pokemon-hub-item-nav')
  await expect(hubNav).toContainText(hub.name)
  await expect(hubNav.getByRole('button', { name: `Renomear ${hub.name}` })).toBeVisible()
  await expect(hubNav.getByRole('button', { name: `Excluir ${hub.name}` })).toHaveCount(0)
  const deleteButton = pane(page, 1).getByRole('button', { name: `Excluir ${hub.name}` })
  await expect(deleteButton).toBeVisible()
  const addButton = pane(page, 1).getByRole('button', { name: 'Criar Perfil do Hub' })
  const addBounds = await addButton.boundingBox()
  const deleteBounds = await deleteButton.boundingBox()
  expect(Math.abs(addBounds.y - deleteBounds.y)).toBeLessThanOrEqual(1)
  expect(deleteBounds.x).toBeGreaterThan(addBounds.x)
  const navBounds = await hubNav.boundingBox()
  expect(Math.abs(navBounds.x - grid.x)).toBeLessThanOrEqual(1)
  expect(Math.abs(navBounds.width - grid.width)).toBeLessThanOrEqual(1)
  expect(navBounds.height).toBeLessThanOrEqual(40)
  const navTitleBounds = await hubNav.getByRole('heading', { name: hub.name }).boundingBox()
  expect(Math.abs(navTitleBounds.x + navTitleBounds.width / 2 - navBounds.x - navBounds.width / 2)).toBeLessThanOrEqual(1)
  await pane(page, 1).getByRole('button', { name: 'Pokémons', exact: true }).click()
  const summary = pane(page, 1).locator('.pokemon-hub-profile-summary')
  await expect(summary.getByRole('button', { name: `Renomear ${hub.name}` })).toBeVisible()
  await expect(summary.getByRole('button', { name: `Excluir ${hub.name}` })).toHaveCount(0)
  const summaryBounds = await summary.boundingBox()
  expect(Math.abs(summaryBounds.x - grid.x)).toBeLessThanOrEqual(1)
  expect(Math.abs(summaryBounds.width - grid.width)).toBeLessThanOrEqual(1)
  expect(Math.abs(summaryBounds.height - navBounds.height)).toBeLessThanOrEqual(1)
  const summaryTitleBounds = await summary.getByRole('heading', { name: hub.name }).boundingBox()
  expect(Math.abs(summaryTitleBounds.x + summaryTitleBounds.width / 2 - summaryBounds.x - summaryBounds.width / 2)).toBeLessThanOrEqual(1)
  await pane(page, 1).getByRole('button', { name: 'Itens', exact: true }).click()
  const saveGrid = await pane(page, 0).locator('.pokemon-item-grid').boundingBox()
  expect(Math.abs(grid.y - saveGrid.y)).toBeLessThanOrEqual(2)

  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, hub.name, 0))
  const deposit = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(deposit.getByRole('spinbutton')).toHaveValue('10')
  await expect(deposit.locator('.pokemon-item-transfer-identity img.pokemon-item-sprite')).toBeVisible()
  await expect(deposit.locator('.pokemon-item-transfer-limit')).toHaveText('/ 10')
  await deposit.getByRole('spinbutton').fill('4')
  await deposit.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0]?.quantity).toBe(4)
  expect((await itemOrder('ruby-hub-items-source', 'items')).slots[0].quantity).toBe(6)

  await drag(page, hubItemSlot(page, 1, hub.name, 0), itemSlot(page, 0, 'Itens', 0))
  const withdrawal = pane(page, 0).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(withdrawal.getByRole('spinbutton')).toHaveValue('4')
  await withdrawal.getByRole('spinbutton').fill('2')
  await withdrawal.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-hub-items-source', 'items')).slots[0].quantity).toBe(8)
  expect((await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0].quantity).toBe(2)
  await addPane(page)
  await expect.poll(async () => {
    const nextTabs = await pane(page, 1).locator('.pokemon-pane-tabs').boundingBox()
    const nextNav = await pane(page, 1).locator('.pokemon-hub-item-nav').boundingBox()
    const nextGrid = await pane(page, 1).locator('.pokemon-hub-item-grid').boundingBox()
    return nextTabs && nextNav && nextGrid ? [Math.round(nextTabs.x - nextGrid.x), Math.round(nextTabs.width - nextGrid.width), Math.round(nextNav.y - nextTabs.y - nextTabs.height), Math.round(nextGrid.y - nextNav.y - nextNav.height), nextGrid.width < grid.width] : null
  }).toEqual([0, 0, 8, 8, true])
  const profileUrl = `${process.env.E2E_API_URL}/api/pokemon-hub/profiles/${hub.hubProfileId}`
  expect((await fetch(profileUrl, { method: 'DELETE' })).status).toBe(409)
  await closeWorkspace(page)
  const discarded = await fetch(`${profileUrl}?discardOccupied=true`, { method: 'DELETE' })
  expect(discarded.status).toBe(200)
  expect((await discarded.json()).discardedItemCount).toBe(1)
  expect((await fetch(profileUrl)).status).toBe(404)
})

test('Hub-to-Hub drops use empty slots, merge equal items and preserve gaps after reorder', async ({ page }) => {
  const first = await createHubProfile('Itens A')
  const second = await createHubProfile('Itens B')
  await openWorkspace(page)
  await selectItemSave(page, 0, 'sapphire-hub-items-target')
  await addPane(page)
  await selectHub(page, 1, first)
  await addPane(page)
  await selectHub(page, 2, second)
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  for (const index of [1, 2]) await pane(page, index).getByRole('button', { name: 'Itens', exact: true }).click()
  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, first.name, 0))
  await pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ }).getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(first.hubProfileId)).profile.itemInventory.slots[0]?.quantity).toBe(10)
  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 2, second.name, 0))
  await pane(page, 2).getByRole('dialog', { name: /Transferir Antidote/ }).getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[0]?.itemKey).toBe('antidote')
  await drag(page, hubItemSlot(page, 1, first.name, 0), hubItemSlot(page, 2, second.name, 0))
  const prompt = pane(page, 2).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt.getByRole('spinbutton')).toHaveValue('10')
  await prompt.getByRole('spinbutton').fill('3')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[1]?.quantity).toBe(3)
  await drag(page, hubItemSlot(page, 2, second.name, 1), hubItemSlot(page, 2, second.name, 5))
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[5]?.quantity).toBe(3)
  expect((await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[1]).toBeUndefined()
  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 2, second.name, 3))
  await pane(page, 2).getByRole('dialog', { name: /Transferir Burn Heal/ }).getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[3]?.itemKey).toBe('burn-heal')
  expect((await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[1]).toBeUndefined()
  await drag(page, hubItemSlot(page, 1, first.name, 0), hubItemSlot(page, 2, second.name, 0))
  const merge = pane(page, 2).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(merge.getByRole('spinbutton')).toHaveValue('7')
  await merge.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[5]?.quantity).toBe(10)
  expect((await readHubProfile(first.hubProfileId)).profile.itemInventory.slots[0]).toBeUndefined()
})

test('Hub-to-save never exceeds the destination stack, even with a forged quantity', async ({ page }) => {
  const hub = await createHubProfile('Limite da pilha')
  const opening = page.waitForResponse(response => /\/pokemon-hub\/sessions$/.test(new URL(response.url()).pathname) && response.status() === 201)
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-hub-stack-source')
  const { sessionId } = await (await opening).json()
  await addPane(page)
  await selectItemSave(page, 1, 'emerald-hub-nearfull')
  await addPane(page)
  await selectHub(page, 2, hub)
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  await pane(page, 2).getByRole('button', { name: 'Itens', exact: true }).click()

  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 2, hub.name, 0))
  await pane(page, 2).getByRole('dialog', { name: /Transferir Potion/ }).getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0]?.quantity).toBe(10)

  const sourceBefore = (await readHubProfile(hub.hubProfileId)).profile.itemInventory
  const destinationBefore = await readItemSave('emerald-hub-nearfull')
  const url = `${process.env.E2E_API_URL}/api/pokemon-hub/sessions/${sessionId}/items/transfer`
  const payload = {
    source: { hubProfileId: hub.hubProfileId, expectedItemRevision: sourceBefore.revision },
    destination: { gameId: itemProfiles['emerald-hub-nearfull'].gameId, profileId: itemProfiles['emerald-hub-nearfull'].profileId, expectedSaveRevision: destinationBefore.revision },
    area: 'items', fromSlot: 0, toSlot: 0, quantity: 10,
  }
  for (const quantity of [10, 11, 0, -1, 1.5, Number.MAX_SAFE_INTEGER + 1]) {
    const forged = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...payload, quantity }) })
    expect(forged.status, `${quantity}: ${await forged.clone().text()}`).toBe(400)
  }
  const wrongPocket = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...payload, area: 'poke-balls', quantity: 1 }) })
  expect(wrongPocket.status, await wrongPocket.clone().text()).toBe(400)
  expect((await readHubProfile(hub.hubProfileId)).profile.itemInventory).toEqual(sourceBefore)
  expect((await readItemSave('emerald-hub-nearfull')).bytes).toEqual(destinationBefore.bytes)

  await drag(page, hubItemSlot(page, 2, hub.name, 0), itemSlot(page, 1, 'Itens', 0))
  const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(prompt.getByRole('spinbutton')).toHaveValue('9')
  await prompt.getByRole('spinbutton').fill('10')
  await expect(prompt.getByRole('button', { name: 'Transferir' })).toBeDisabled()
  await prompt.getByRole('spinbutton').fill('9')
  await prompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('emerald-hub-nearfull', 'items')).slots[0].quantity).toBe(99)
  expect((await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0].quantity).toBe(1)
  const fullSave = await readItemSave('emerald-hub-nearfull')
  await drag(page, hubItemSlot(page, 2, hub.name, 0), itemSlot(page, 1, 'Itens', 0))
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  expect((await readItemSave('emerald-hub-nearfull')).bytes).toEqual(fullSave.bytes)
})

test('Hub-to-save fills the final distinct slot, rejects a new type, and still merges an existing stack', async ({ page }) => {
  const hub = await createHubProfile('Limite de tipos')
  const opening = page.waitForResponse(response => /\/pokemon-hub\/sessions$/.test(new URL(response.url()).pathname) && response.status() === 201)
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-hub-capacity-source')
  const { sessionId } = await (await opening).json()
  await addPane(page)
  await selectItemSave(page, 1, 'ruby-hub-items-19')
  await addPane(page)
  await selectHub(page, 2, hub)
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  await pane(page, 2).getByRole('button', { name: 'Itens', exact: true }).click()

  for (const [sourceSlot, itemName, hubSlot] of [[0, 'Potion', 0], [0, 'Antidote', 1]]) {
    await drag(page, itemSlot(page, 0, 'Itens', sourceSlot), hubItemSlot(page, 2, hub.name, hubSlot))
    await pane(page, 2).getByRole('dialog', { name: new RegExp(`Transferir ${itemName}`) }).getByRole('button', { name: 'Transferir' }).click()
    await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[hubSlot]?.itemKey).toBe(itemName.toLowerCase())
  }
  await drag(page, hubItemSlot(page, 2, hub.name, 0), itemSlot(page, 1, 'Itens', 10))
  const first = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await first.getByRole('spinbutton').fill('1')
  await first.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-hub-items-19', 'items')).slots.filter(slot => slot.nativeId).length).toBe(20)
  const before = await readItemSave('ruby-hub-items-19')
  const hubBefore = (await readHubProfile(hub.hubProfileId)).profile.itemInventory
  await drag(page, hubItemSlot(page, 2, hub.name, 1), itemSlot(page, 1, 'Itens', 0))
  await expect(pane(page, 1).getByRole('dialog', { name: /Transferir/ })).toHaveCount(0)
  const forged = await fetch(`${process.env.E2E_API_URL}/api/pokemon-hub/sessions/${sessionId}/items/transfer`, {
    method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({
      source: { hubProfileId: hub.hubProfileId, expectedItemRevision: hubBefore.revision },
      destination: { gameId: itemProfiles['ruby-hub-items-19'].gameId, profileId: itemProfiles['ruby-hub-items-19'].profileId, expectedSaveRevision: before.revision },
      area: 'items', fromSlot: 1, toSlot: 0, quantity: 1,
    }),
  })
  expect(forged.status, await forged.clone().text()).toBe(400)
  expect((await readItemSave('ruby-hub-items-19')).bytes).toEqual(before.bytes)
  expect((await readHubProfile(hub.hubProfileId)).profile.itemInventory).toEqual(hubBefore)

  await drag(page, hubItemSlot(page, 2, hub.name, 0), itemSlot(page, 1, 'Itens', 10))
  const merge = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(merge.getByRole('spinbutton')).toHaveValue('9')
  await merge.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await itemOrder('ruby-hub-items-19', 'items')).slots[10].quantity).toBe(10)
  expect((await itemOrder('ruby-hub-items-19', 'items')).slots.filter(slot => slot.nativeId).length).toBe(20)
  expect((await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0]).toBeUndefined()
})

test('parallel and replayed Hub transfers cannot credit the destination twice', async ({ page }) => {
  const first = await createHubProfile('Origem concorrente')
  const second = await createHubProfile('Destino concorrente')
  const opening = page.waitForResponse(response => /\/pokemon-hub\/sessions$/.test(new URL(response.url()).pathname) && response.status() === 201)
  await openWorkspace(page)
  await selectItemSave(page, 0, 'sapphire-hub-concurrent-source')
  const { sessionId } = await (await opening).json()
  await addPane(page)
  await selectHub(page, 1, first)
  await addPane(page)
  await selectHub(page, 2, second)
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  await pane(page, 1).getByRole('button', { name: 'Itens', exact: true }).click()
  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, first.name, 0))
  await pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ }).getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(first.hubProfileId)).profile.itemInventory.slots[0]?.quantity).toBe(10)
  const source = (await readHubProfile(first.hubProfileId)).profile.itemInventory
  const destination = (await readHubProfile(second.hubProfileId)).profile.itemInventory
  const url = `${process.env.E2E_API_URL}/api/pokemon-hub/sessions/${sessionId}/items/transfer`
  const payload = { source: { hubProfileId: first.hubProfileId, expectedItemRevision: source.revision },
    destination: { hubProfileId: second.hubProfileId, expectedItemRevision: destination.revision }, fromSlot: 0, toSlot: 0, quantity: 7 }
  const post = () => fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) })
  const responses = await Promise.all([post(), post()])
  expect(responses.map(response => response.status).sort()).toEqual([200, 412])
  expect((await readHubProfile(first.hubProfileId)).profile.itemInventory.slots[0].quantity).toBe(3)
  expect((await readHubProfile(second.hubProfileId)).profile.itemInventory.slots[0].quantity).toBe(7)
  expect((await post()).status).toBe(412)
  const current = (await readHubProfile(first.hubProfileId)).profile.itemInventory
  const destinationCurrent = (await readHubProfile(second.hubProfileId)).profile.itemInventory
  const overdrawn = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({
    ...payload, source: { ...payload.source, expectedItemRevision: current.revision },
    destination: { ...payload.destination, expectedItemRevision: destinationCurrent.revision }, quantity: 4,
  }) })
  expect(overdrawn.status, await overdrawn.clone().text()).toBe(400)
  expect((await readHubProfile(first.hubProfileId)).profile.itemInventory).toEqual(current)
  expect((await readHubProfile(second.hubProfileId)).profile.itemInventory).toEqual(destinationCurrent)
})

test('Ruby and Sapphire deposits merge by itemKey after Hub reordering and remain merged on reopen', async ({ page }) => {
  const hub = await createHubProfile('Identidade entre títulos')
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-hub-merge-source')
  await addPane(page)
  await selectItemSave(page, 1, 'sapphire-hub-merge-source')
  await addPane(page)
  await selectHub(page, 2, hub)
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  await selectItemArea(page, 1, 'Itens')
  await pane(page, 2).getByRole('button', { name: 'Itens', exact: true }).click()

  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 2, hub.name, 0))
  const ruby = pane(page, 2).getByRole('dialog', { name: /Transferir Potion/ })
  await ruby.getByRole('spinbutton').fill('4')
  await ruby.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0]?.quantity).toBe(4)
  await drag(page, itemSlot(page, 0, 'Itens', 1), hubItemSlot(page, 2, hub.name, 2))
  await pane(page, 2).getByRole('dialog', { name: /Transferir Antidote/ }).getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[2]?.itemKey).toBe('antidote')
  await drag(page, hubItemSlot(page, 2, hub.name, 0), hubItemSlot(page, 2, hub.name, 5))
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[5]?.quantity).toBe(4)

  await drag(page, itemSlot(page, 1, 'Itens', 0), hubItemSlot(page, 2, hub.name, 2))
  const sapphire = pane(page, 2).getByRole('dialog', { name: /Transferir Potion/ })
  await expect(sapphire.getByRole('spinbutton')).toHaveValue('10')
  await sapphire.getByRole('spinbutton').fill('6')
  await sapphire.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[5]?.quantity).toBe(10)
  const slots = (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots
  expect(slots[0]).toBeUndefined()
  expect(slots[2].itemKey).toBe('antidote')
  expect(Object.values(slots).filter(slot => slot.itemKey === 'potion')).toHaveLength(1)
  expect((await itemOrder('ruby-hub-merge-source', 'items')).slots[0].quantity).toBe(6)
  expect((await itemOrder('sapphire-hub-merge-source', 'items')).slots[0].quantity).toBe(4)
  await closeWorkspace(page)
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-hub-merge-source')
  await addPane(page)
  await selectHub(page, 1, hub)
  await pane(page, 1).getByRole('button', { name: 'Itens', exact: true }).click()
  await expect(hubItemSlot(page, 1, hub.name, 5)).toHaveAttribute('aria-label', /Potion/)
  expect((await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[5].quantity).toBe(10)
})

test('queues two item deposits without blocking the workspace and projects them before the first response', async ({ page }) => {
  const hub = await createHubProfile('Fila sem bloqueio')
  let releaseFirst
  let signalFirst
  const firstBlocked = new Promise(resolve => { releaseFirst = resolve })
  const firstStarted = new Promise(resolve => { signalFirst = resolve })
  let requests = 0
  await page.route('**/items/transfer', async route => {
    requests++
    if (requests === 1) { signalFirst(); await firstBlocked }
    await route.continue()
  })
  try {
    await openWorkspace(page)
    await selectItemSave(page, 0, 'ruby-item-queue-success')
    await addPane(page)
    await selectHub(page, 1, hub)
    await openItems(page, 0)
    await openItems(page, 1)
    await selectItemArea(page, 0, 'Itens')
    await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, hub.name, 0))
    await pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ }).getByRole('button', { name: 'Transferir' }).click()
    await firstStarted
    await expect(page.getByRole('status', { name: 'Processando alteração do workspace' })).toHaveCount(0)
    await expect(hubItemSlot(page, 1, hub.name, 0)).toHaveAttribute('aria-label', /Potion/)
    await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, hub.name, 1))
    await pane(page, 1).getByRole('dialog', { name: /Transferir Antidote/ }).getByRole('button', { name: 'Transferir' }).click()
    await expect(hubItemSlot(page, 1, hub.name, 1)).toHaveAttribute('aria-label', /Antidote/)
    expect(requests).toBe(1)
  } finally { releaseFirst() }
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[1]?.itemKey).toBe('antidote')
  expect(requests).toBe(2)
})

test('rolls back a rejected item deposit, shows its reason and continues the next queued deposit', async ({ page }) => {
  const hub = await createHubProfile('Fila com falha')
  let rejectFirst
  let signalFirst
  const firstBlocked = new Promise(resolve => { rejectFirst = resolve })
  const firstStarted = new Promise(resolve => { signalFirst = resolve })
  let requests = 0
  await page.route('**/items/transfer', async route => {
    requests++
    if (requests === 1) {
      signalFirst()
      await firstBlocked
      await route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ error: 'Falha simulada na transferência', code: 'E2E_TEST_FAILURE' }) })
    } else await route.continue()
  })
  try {
    await openWorkspace(page)
    await selectItemSave(page, 0, 'ruby-item-queue-failure')
    await addPane(page)
    await selectHub(page, 1, hub)
    await openItems(page, 0)
    await openItems(page, 1)
    await selectItemArea(page, 0, 'Itens')
    await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, hub.name, 0))
    await pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ }).getByRole('button', { name: 'Transferir' }).click()
    await firstStarted
    await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, hub.name, 1))
    await pane(page, 1).getByRole('dialog', { name: /Transferir Antidote/ }).getByRole('button', { name: 'Transferir' }).click()
    await expect(hubItemSlot(page, 1, hub.name, 0)).toHaveAttribute('aria-label', /Potion/)
    await expect(hubItemSlot(page, 1, hub.name, 1)).toHaveAttribute('aria-label', /Antidote/)
  } finally { rejectFirst() }
  await expect(page.getByText('Falha simulada na transferência')).toBeVisible()
  await expect(hubItemSlot(page, 1, hub.name, 0)).toHaveAttribute('aria-label', /vazia/)
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[1]?.itemKey).toBe('antidote')
  expect((await itemOrder('ruby-item-queue-failure', 'items')).slots[0].itemKey).toBe('potion')
  expect(requests).toBe(2)
})

test('five queued deposits survive closing and reopening the Hub while the first request is delayed', async ({ page }) => {
  test.setTimeout(120_000)
  const hub = await createHubProfile('Fila durante fechamento')
  let releaseFirst
  let signalFirst
  const firstBlocked = new Promise(resolve => { releaseFirst = resolve })
  const firstStarted = new Promise(resolve => { signalFirst = resolve })
  let requests = 0
  const responses = []
  await page.route('**/items/transfer', async route => {
    requests++
    if (requests === 1) { signalFirst(); await firstBlocked }
    await route.continue()
  })
  page.on('response', response => {
    if (/\/items\/transfer$/.test(new URL(response.url()).pathname)) responses.push(response.status())
  })
  try {
    await openWorkspace(page)
    await selectItemSave(page, 0, 'ruby-item-race-close')
    await addPane(page)
    await selectHub(page, 1, hub)
    await openItems(page, 0)
    await openItems(page, 1)
    await selectItemArea(page, 0, 'Itens')
    for (let count = 1; count <= 5; count++) {
      await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, hub.name, 0))
      const prompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
      await prompt.getByRole('spinbutton').fill('1')
      await prompt.getByRole('button', { name: 'Transferir' }).click()
      if (count === 1) await firstStarted
      await expect(hubItemSlot(page, 1, hub.name, 0)).toHaveAttribute('aria-label', new RegExp(`Potion, ${count}$`))
    }
    expect(requests).toBe(1)
    await page.getByRole('button', { name: 'Fechar Pokémon Hub' }).click()
    await expect(page.getByRole('dialog', { name: 'Pokémon Hub' })).toBeVisible()
  } finally { releaseFirst() }
  await expect(page.getByRole('dialog', { name: 'Pokémon Hub' })).toHaveCount(0)
  await expect.poll(() => requests).toBe(5)
  expect(responses).toEqual([200, 200, 200, 200, 200])
  expect((await itemOrder('ruby-item-race-close', 'items')).slots[0].quantity).toBe(5)
  expect((await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0].quantity).toBe(5)
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-item-race-close')
  await addPane(page)
  await selectHub(page, 1, hub)
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  await expect(itemSlot(page, 0, 'Itens', 0)).toHaveAttribute('aria-label', /Potion, 5/)
  await expect(hubItemSlot(page, 1, hub.name, 0)).toHaveAttribute('aria-label', /Potion, 5/)
})

test('repeated item swaps preserve every stack and their order across Hub reopen', async ({ page }) => {
  test.setTimeout(120_000)
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-item-race-reorder')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  const initial = await itemOrder('ruby-item-race-reorder', 'items')
  for (let move = 1; move <= 12; move++) {
    await drag(page, itemSlot(page, 0, 'Itens', 0), itemSlot(page, 0, 'Itens', 1))
    await expect.poll(async () => (await itemOrder('ruby-item-race-reorder', 'items')).revision).toBe(initial.revision + move)
  }
  const final = await itemOrder('ruby-item-race-reorder', 'items')
  expect(final.slots.slice(0, 3).map(slot => [slot.itemKey, slot.quantity])).toEqual(initial.slots.slice(0, 3).map(slot => [slot.itemKey, slot.quantity]))
  expect(final.slots.slice(3).every(slot => !slot.nativeId)).toBe(true)
  await closeWorkspace(page)
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-item-race-reorder')
  await openItems(page, 0)
  await selectItemArea(page, 0, 'Itens')
  expect((await itemOrder('ruby-item-race-reorder', 'items')).slots).toEqual(final.slots)
  await expect(itemSlot(page, 0, 'Itens', 0)).toHaveAttribute('aria-label', /Potion, 10/)
})

test('late response from an old close does not replace an already reopened item session', async ({ page }) => {
  test.setTimeout(120_000)
  const hub = await createHubProfile('Fechamento atrasado')
  await openWorkspace(page)
  await selectItemSave(page, 0, 'ruby-item-race-reopen')
  await addPane(page)
  await selectHub(page, 1, hub)
  await openItems(page, 0)
  await openItems(page, 1)
  await selectItemArea(page, 0, 'Itens')
  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, hub.name, 0))
  const firstPrompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await firstPrompt.getByRole('spinbutton').fill('1')
  await firstPrompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0]?.quantity).toBe(1)

  let releaseClose
  let signalClose
  let signalDelivered
  const closeBlocked = new Promise(resolve => { releaseClose = resolve })
  const closeStarted = new Promise(resolve => { signalClose = resolve })
  const closeDelivered = new Promise(resolve => { signalDelivered = resolve })
  let oldCloseStatus = null
  await page.route('**/pokemon-hub/sessions/*/close', async route => {
    const response = await route.fetch()
    oldCloseStatus = response.status()
    signalClose()
    await closeBlocked
    await route.fulfill({ response })
    signalDelivered()
  })
  try {
    await page.getByRole('button', { name: 'Fechar Pokémon Hub' }).click()
    await closeStarted
    await expect(page.getByRole('dialog', { name: 'Pokémon Hub' })).toHaveCount(0)
    forgetSelectedSaves(page)
    await page.getByRole('button', { name: 'Abrir Pokémon Hub' }).click()
    await expect(page.getByRole('dialog', { name: 'Pokémon Hub' })).toBeVisible()
    await selectItemSave(page, 0, 'ruby-item-race-reopen')
    await addPane(page)
    await selectHub(page, 1, hub)
    await openItems(page, 0)
    await openItems(page, 1)
    await selectItemArea(page, 0, 'Itens')
    await expect(hubItemSlot(page, 1, hub.name, 0)).toHaveAttribute('aria-label', /Potion, 1/)
  } finally {
    releaseClose()
    await closeDelivered
    await page.unroute('**/pokemon-hub/sessions/*/close')
  }
  expect(oldCloseStatus).toBe(200)
  await drag(page, itemSlot(page, 0, 'Itens', 0), hubItemSlot(page, 1, hub.name, 0))
  const secondPrompt = pane(page, 1).getByRole('dialog', { name: /Transferir Potion/ })
  await secondPrompt.getByRole('spinbutton').fill('1')
  await secondPrompt.getByRole('button', { name: 'Transferir' }).click()
  await expect.poll(async () => (await readHubProfile(hub.hubProfileId)).profile.itemInventory.slots[0]?.quantity).toBe(2)
  expect((await itemOrder('ruby-item-race-reopen', 'items')).slots[0].quantity).toBe(8)
})
