import { test, expect } from '@playwright/test'
import { pokemonGen3Adapter } from '../../packages/pokemon-gen3-adapter.mjs'
import { addPane, boxSlot, closeWorkspace, createHubProfile, drag, hubSlot, occupiedIds, openWorkspace, pane, partySlot, readHubProfile, readLayout, readSave, saveBoxSlot, selectHub, selectSave } from './helpers.mjs'
import { watchSnapshots } from './snapshot-audit.mjs'

const audits = new WeakMap()
test.beforeEach(async ({ page }) => { audits.set(page, await watchSnapshots(page)) })
test.afterEach(async ({ page }, testInfo) => { await audits.get(page)(testInfo) })

test('move dentro de uma Box e persiste os bytes nativos após fechar', async ({ page }) => {
  const before = await readLayout('intra')
  const pokemonId = before.boxes[0].slots[0].pokemonInstanceId
  const originalIds = await occupiedIds('intra')
  expect(pokemonId).toBeTruthy()
  await openWorkspace(page)
  await selectSave(page, 0, 'intra')
  await drag(page, boxSlot(page, 0, 0), boxSlot(page, 0, 5))
  await expect(boxSlot(page, 0, 0)).toHaveAccessibleName(/vazia/)
  await expect(boxSlot(page, 0, 5)).toHaveAccessibleName(/ocupada/)
  await closeWorkspace(page)
  await expect.poll(async () => (await readLayout('intra')).boxes[0].slots[5].pokemonInstanceId).toBe(pokemonId)
  const after = await readLayout('intra')
  expect(after.boxes[0].slots[0].pokemonInstanceId).toBeFalsy()
  expect((await occupiedIds('intra')).sort()).toEqual(originalIds.sort())
  const saved = await readSave('intra')
  expect(saved.revision).toBeGreaterThan(1)
  expect(pokemonGen3Adapter.readSlot(saved.bytes, 0, 0)).toBeNull()
  expect(pokemonGen3Adapter.readSlot(saved.bytes, 0, 5)?.canonical.species).toBe(25)
})

test('Save → perfil Hub → Save conserva identidade e flush', async ({ page }) => {
  const hub = await createHubProfile('E2E Roundtrip')
  const before = await readLayout('roundtrip')
  const pokemonId = before.boxes[0].slots[0].pokemonInstanceId
  const originalIds = await occupiedIds('roundtrip')
  await openWorkspace(page)
  await selectSave(page, 0, 'roundtrip')
  await addPane(page)
  await selectHub(page, 1, hub)
  await drag(page, boxSlot(page, 0, 0), hubSlot(page, 1, hub, 0))
  await expect(hubSlot(page, 1, hub, 0)).toHaveAccessibleName(/ocupada/)
  await drag(page, hubSlot(page, 1, hub, 0), boxSlot(page, 0, 5))
  await expect(boxSlot(page, 0, 5)).toHaveAccessibleName(/ocupada/)
  await closeWorkspace(page)
  await expect.poll(async () => (await readLayout('roundtrip')).boxes[0].slots[5].pokemonInstanceId).toBe(pokemonId)
  expect(Object.values((await readHubProfile(hub.hubProfileId)).profile.grid.entries)).toHaveLength(0)
  expect((await occupiedIds('roundtrip')).sort()).toEqual(originalIds.sort())
  expect(pokemonGen3Adapter.readSlot((await readSave('roundtrip')).bytes, 0, 5)?.canonical.species).toBe(25)
})

test('Save de um perfil → Save de outro perfil preserva a contagem global', async ({ page }) => {
  const from = await readLayout('direct-a')
  const pokemonId = from.boxes[0].slots[0].pokemonInstanceId
  const ids = [...await occupiedIds('direct-a'), ...await occupiedIds('direct-b', 'direct-a')].sort()
  await openWorkspace(page)
  await selectSave(page, 0, 'direct-a')
  await addPane(page)
  await selectSave(page, 1, 'direct-b')
  await drag(page, boxSlot(page, 0, 0), boxSlot(page, 1, 5))
  await expect(boxSlot(page, 1, 5)).toHaveAccessibleName(/ocupada/)
  await closeWorkspace(page)
  await expect.poll(async () => (await readLayout('direct-b', 'direct-a')).boxes[0].slots[5].pokemonInstanceId).toBe(pokemonId)
  expect([...await occupiedIds('direct-a'), ...await occupiedIds('direct-b', 'direct-a')].sort()).toEqual(ids)
  expect(pokemonGen3Adapter.readSlot((await readSave('direct-b')).bytes, 0, 5)?.canonical.species).toBe(25)
})

test('destino Hub ocupado e entrada na Party são recusados sem mutação', async ({ page }) => {
  const initial = await readLayout('negative')
  const originalIds = await occupiedIds('negative')
  const hub = await createHubProfile('E2E Negative')
  await openWorkspace(page)
  await selectSave(page, 0, 'negative')
  await drag(page, boxSlot(page, 0, 0), partySlot(page, 0, 2))
  await expect(boxSlot(page, 0, 0)).toHaveAccessibleName(/ocupada/)
  await expect(partySlot(page, 0, 2)).toHaveAccessibleName(/vazia/)
  await addPane(page)
  await selectHub(page, 1, hub)
  await drag(page, boxSlot(page, 0, 0), hubSlot(page, 1, hub, 0))
  await expect(hubSlot(page, 1, hub, 0)).toHaveAccessibleName(/ocupada/)
  await drag(page, boxSlot(page, 0, 1), hubSlot(page, 1, hub, 0))
  await expect(boxSlot(page, 0, 1)).toHaveAccessibleName(/ocupada/)
  await closeWorkspace(page)
  const after = await readLayout('negative')
  expect(after.boxes[0].slots[0].pokemonInstanceId).toBeFalsy()
  expect(after.boxes[0].slots[1].pokemonInstanceId).toBe(initial.boxes[0].slots[1].pokemonInstanceId)
  expect(after.party[2].pokemonInstanceId).toBeFalsy()
  const hubEntries = Object.values((await readHubProfile(hub.hubProfileId)).profile.grid.entries)
  expect(hubEntries.map(entry => entry.pokemonInstanceId)).toEqual([initial.boxes[0].slots[0].pokemonInstanceId])
  expect([...await occupiedIds('negative'), ...hubEntries.map(entry => entry.pokemonInstanceId)].sort()).toEqual(originalIds.sort())
})

test('arrastes sucessivos seguidos de close imediato conservam todos os IDs', async ({ page }) => {
  const before = await readLayout('rapid')
  const ids = await occupiedIds('rapid')
  await openWorkspace(page)
  await selectSave(page, 0, 'rapid')
  for (let slot = 0; slot < 3; slot += 1) {
    await drag(page, boxSlot(page, 0, slot), boxSlot(page, 0, slot + 5))
  }
  await closeWorkspace(page)
  await expect.poll(async () => (await readLayout('rapid')).boxes[0].slots.slice(5, 8).map(slot => slot.pokemonInstanceId)).toEqual(before.boxes[0].slots.slice(0, 3).map(slot => slot.pokemonInstanceId))
  expect((await occupiedIds('rapid')).sort()).toEqual(ids.sort())
  const saved = await readSave('rapid')
  expect(saved.revision).toBeGreaterThan(1)
  expect([5, 6, 7].map(slot => pokemonGen3Adapter.readSlot(saved.bytes, 0, slot)?.canonical.species)).toEqual([25, 64, 133])
})

test('fechar um painel logo após o drag preserva o Save e a sessão restante', async ({ page }) => {
  const before = await readLayout('profile-a')
  await openWorkspace(page)
  await selectSave(page, 0, 'profile-a')
  await addPane(page)
  await selectSave(page, 1, 'profile-b')
  await drag(page, boxSlot(page, 0, 0), boxSlot(page, 0, 5))
  await pane(page, 0).getByRole('button', { name: 'Fechar container' }).click()
  await expect(page.locator('.pokemon-workspace-pane')).toHaveCount(1)
  await closeWorkspace(page)
  await expect.poll(async () => (await readLayout('profile-a')).boxes[0].slots[5].pokemonInstanceId).toBe(before.boxes[0].slots[0].pokemonInstanceId)
  expect(pokemonGen3Adapter.readSlot((await readSave('profile-a')).bytes, 0, 5)?.canonical.species).toBe(25)
})

test('swap entre dois slots ocupados da mesma Box preserva ambos os records', async ({ page }) => {
  const before = await readLayout('swap')
  const first = before.boxes[0].slots[0].pokemonInstanceId
  const second = before.boxes[0].slots[1].pokemonInstanceId
  await openWorkspace(page)
  await selectSave(page, 0, 'swap')
  await drag(page, boxSlot(page, 0, 0), boxSlot(page, 0, 1))
  await closeWorkspace(page)
  await expect.poll(async () => (await readLayout('swap')).boxes[0].slots.slice(0, 2).map(slot => slot.pokemonInstanceId)).toEqual([second, first])
  await expect.poll(async () => {
    const bytes = (await readSave('swap')).bytes
    return [0, 1].map(slot => pokemonGen3Adapter.readSlot(bytes, 0, slot)?.canonical.species)
  }).toEqual([64, 25])
})

test('Party → Box compacta a Party e mantém ao menos um Pokémon', async ({ page }) => {
  const before = await readLayout('party')
  const moved = before.party[0].pokemonInstanceId
  const survivor = before.party[1].pokemonInstanceId
  await openWorkspace(page)
  await selectSave(page, 0, 'party')
  await drag(page, partySlot(page, 0, 0), boxSlot(page, 0, 5))
  await closeWorkspace(page)
  await expect.poll(async () => (await readLayout('party')).boxes[0].slots[5].pokemonInstanceId).toBe(moved)
  const after = await readLayout('party')
  expect(after.party[0].pokemonInstanceId).toBe(survivor)
  expect(after.party[1].pokemonInstanceId).toBeFalsy()
  expect((await occupiedIds('party')).sort()).toEqual([...before.party, ...before.boxes.flatMap(box => box.slots)].map(slot => slot.pokemonInstanceId).filter(Boolean).sort())
  const saved = await readSave('party')
  expect(pokemonGen3Adapter.inspect(saved.bytes, { party: { sectionId: 1, countOffset: 0x234, offset: 0x238, slots: 6, recordBytes: 100 } }).party[0].species).toBe(11)
})

test('Save → Hub A → Hub B conserva a identidade ao reabrir', async ({ page }) => {
  const firstHub = await createHubProfile('E2E Hub A')
  const secondHub = await createHubProfile('E2E Hub B')
  const before = await readLayout('hub-hub')
  const id = before.boxes[0].slots[0].pokemonInstanceId
  await openWorkspace(page)
  await selectSave(page, 0, 'hub-hub')
  await addPane(page)
  await selectHub(page, 1, firstHub)
  await addPane(page)
  await selectHub(page, 2, secondHub)
  await drag(page, boxSlot(page, 0, 0), hubSlot(page, 1, firstHub, 0))
  await drag(page, hubSlot(page, 1, firstHub, 0), hubSlot(page, 2, secondHub, 4))
  await closeWorkspace(page)
  await expect.poll(async () => Object.values((await readHubProfile(secondHub.hubProfileId)).profile.grid.entries).map(entry => entry.pokemonInstanceId)).toEqual([id])
  expect(Object.values((await readHubProfile(firstHub.hubProfileId)).profile.grid.entries)).toHaveLength(0)
  await openWorkspace(page)
  await selectSave(page, 0, 'hub-hub')
  await addPane(page)
  await selectHub(page, 1, secondHub)
  await expect(hubSlot(page, 1, secondHub, 4)).toHaveAccessibleName(/ocupada/)
  await closeWorkspace(page)
})

test('soltar fora de um slot mantém o Save sem alteração', async ({ page }) => {
  const before = await readLayout('outside')
  const savedBefore = await readSave('outside')
  await openWorkspace(page)
  await selectSave(page, 0, 'outside')
  const start = await boxSlot(page, 0, 0).boundingBox()
  const header = await pane(page, 0).locator('.pokemon-pane-header').boundingBox()
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2)
  await page.mouse.down()
  await page.mouse.move(start.x + start.width / 2 + 10, start.y + start.height / 2 + 10, { steps: 4 })
  await page.mouse.move(header.x + header.width / 2, header.y + header.height / 2, { steps: 8 })
  await page.mouse.up()
  await closeWorkspace(page)
  expect((await readLayout('outside')).boxes[0].slots[0].pokemonInstanceId).toBe(before.boxes[0].slots[0].pokemonInstanceId)
  const savedAfter = await readSave('outside')
  expect(savedAfter.revision).toBe(savedBefore.revision)
  expect(savedAfter.bytes).toEqual(savedBefore.bytes)
})

test('último Pokémon da Party não pode ser removido', async ({ page }) => {
  const before = await readLayout('guard')
  const savedBefore = await readSave('guard')
  await openWorkspace(page)
  await selectSave(page, 0, 'guard')
  await drag(page, partySlot(page, 0, 0), boxSlot(page, 0, 5))
  await expect(partySlot(page, 0, 0)).toHaveAccessibleName(/ocupada/)
  await closeWorkspace(page)
  const after = await readLayout('guard')
  expect(after.party[0].pokemonInstanceId).toBe(before.party[0].pokemonInstanceId)
  expect(after.boxes[0].slots[5].pokemonInstanceId).toBeFalsy()
  const savedAfter = await readSave('guard')
  expect(savedAfter.revision).toBe(savedBefore.revision)
  expect(savedAfter.bytes).toEqual(savedBefore.bytes)
})

test('destino ocupado em outro Save não substitui nenhum dos dois Pokémon', async ({ page }) => {
  const source = await readLayout('occupied-a')
  const target = await readLayout('occupied-b', 'occupied-a')
  const sourceSave = await readSave('occupied-a')
  const targetSave = await readSave('occupied-b')
  await openWorkspace(page)
  await selectSave(page, 0, 'occupied-a')
  await addPane(page)
  await selectSave(page, 1, 'occupied-b')
  await drag(page, boxSlot(page, 0, 0), boxSlot(page, 1, 0))
  await closeWorkspace(page)
  expect((await readLayout('occupied-a')).boxes[0].slots[0].pokemonInstanceId).toBe(source.boxes[0].slots[0].pokemonInstanceId)
  expect((await readLayout('occupied-b', 'occupied-a')).boxes[0].slots[0].pokemonInstanceId).toBe(target.boxes[0].slots[0].pokemonInstanceId)
  expect((await readSave('occupied-a')).bytes).toEqual(sourceSave.bytes)
  expect((await readSave('occupied-b')).bytes).toEqual(targetSave.bytes)
})

test('navegação para Box 2 mantém o índice físico correto no movimento', async ({ page }) => {
  const before = await readLayout('boxes')
  const id = before.boxes[1].slots[0].pokemonInstanceId
  await openWorkspace(page)
  await selectSave(page, 0, 'boxes')
  await pane(page, 0).getByRole('button', { name: 'Próxima Box' }).click()
  await expect(pane(page, 0).getByRole('heading', { name: 'Box 2 de 14' })).toBeVisible()
  await drag(page, saveBoxSlot(page, 0, 1, 0), saveBoxSlot(page, 0, 1, 5))
  await closeWorkspace(page)
  await expect.poll(async () => (await readLayout('boxes')).boxes[1].slots[5].pokemonInstanceId).toBe(id)
  expect(pokemonGen3Adapter.readSlot((await readSave('boxes')).bytes, 1, 0)).toBeNull()
  expect(pokemonGen3Adapter.readSlot((await readSave('boxes')).bytes, 1, 5)?.canonical.species).toBe(25)
})
